### ISSUE TITLE
Sign up users

### ISSUE THREAD

**Issue by oguntli** [GrumpOMeter/GrumpONado#9]
## Detailed Description

Sign up users

## Context

Users must be able to sign up

## Tasks
- [x] Main app
- [x] Post request handler to create a user
- [x] Hash and salt password before writing the user
- [x] Save user to DB
- [x] Tests
